### ISSUE TITLE
App doesn't support shortened form of video links

### ISSUE THREAD

**Issue by trevenue44** [McSam-py/YouTube-Video-Downloader#2]
App doesn't recognize shortened form of youtube links as youtube videos.

It is shown in the picture below
![1](https://user-images.githubusercontent.com/55891238/142994582-299ffd1b-6744-4562-a802-34814b7340db.jpg)

**Comment by theMcSam** [comment]
Thank you for letting me know trevenue44.
Issue has been resolved, thank you.
